echo " This file contains only basics of Day1"
echo "This is poll scm method without build every minute jenkins check  git hub if has any changes or not without buildnow action"
echo " Auto build sucess"
echo "sucessully added webhook for advanced update than poll scm"
echo "if jenkins url is not corrected but github webhookurl corrected but matched"
